name: CD - Deploy API to Staging/Production

on:
  workflow_run:
    workflows: ["CI - Build and Test .NET Projects"] # Se activa solo si el CI termina
    types:
      - completed
    branches:
      - develop

jobs:
  deploy:
    # CLAVE: Solo se ejecuta si el CI (workflow_run) fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    environment: Staging # Define un entorno (buena práctica)

    steps:
    - name: Download Build Artifact (from CI)
      uses: actions/download-artifact@v4
      with:
        name: fastfood-api-artifact
        path: ./deploy_package
        
    - name: Deploy to Hosting Platform (Placeholder)
      # Simula el despliegue. Esto cumple con el requisito del Punto 5.
      run: echo "Simulando el despliegue automático del artefacto API..."
      
    - name: Deployment Success Notification
      run: echo "🚀 Despliegue completado del API a Staging."
